name: lezzform Lite

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      contents: read
      pull-requests: read
    outputs:
      docs: ${{ steps.filter.outputs.docs }} 
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**' 

  docs:
    needs: changes
    if: ${{ needs.changes.outputs.docs == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v3
      
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Building docs
        run: |
          cd docs/
          docker buildx build --tag "${{ secrets.DOCKER_IMAGE_DOCS_PRODUCTION }}" .

      - name: Push docs image into Registry
        run: docker push ${{ secrets.DOCKER_IMAGE_DOCS_PRODUCTION }}

      - name: Redeploy Docs
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: 22
          script: |
           docker compose -f ${{ secrets.PATH }} pull
           docker compose -f ${{ secrets.PATH }} down
           docker compose -f ${{ secrets.PATH }} up -d
